"@suspensive/react":
  - "packages/react/**/*"
"@suspensive/react-query":
  - "packages/react-query/**/*"
"@suspensive/react-await":
  - "packages/react-await/**/*"
"@suspensive/react-image":
  - "packages/react-image/**/*"
"docs/v1":
  - "docs/v1**/*"
"docs/v2":
  - "docs/v2**/*"
"visualization":
  - "websites/visualization/**/*"
"eslint":
  - "configs/eslint/**/*"
  - "**/.eslint*"
"tsconfig":
  - "configs/tsconfig/**/*"
  - "**/.tsconfig*"
"dependencies":
  - "pnpm-lock.yaml"
"workflows":
  - ".github/workflows/**/*"
