react:
  - packages/react/**
react-query:
  - packages/react-query/**
websites/docs:
  - websites/docs/**
visualization:
  - websites/visualization/**
eslint:
  - configs/eslint/**
tsconfig:
  - configs/tsconfig/**
dependencies:
  - pnpm-lock.yaml
workflows:
  - .github/workflows/**
