"@suspensive/react":
  - "packages/react/**/*"
"@suspensive/react-query":
  - "packages/react-query/**/*"
"@suspensive/await":
  - "packages/await/**/*"
"documentation":
  - "docs/**/*"
"visualization":
  - "websites/visualization/**/*"
"eslint":
  - "configs/eslint/**/*"
  - "**/.eslint*"
"tsconfig":
  - "configs/tsconfig/**/*"
  - "**/.tsconfig*"
"dependencies":
  - "pnpm-lock.yaml"
"workflows":
  - ".github/workflows/**/*"
