packages:
  - "configs/*"
  - "docs/*"
  - "examples/*"
  - "packages/*"

catalog:
  "babel-jest": "^29.7.0"
  "jest": "^29.7.0"
  # next
  "next": "^15.0.4"
  "@next/eslint-plugin-next": "^15.0.4"
  "sharp": "^0.33.5"

  # tailwindcss
  "autoprefixer": "^10.4.20"
  "postcss": "^8.4.49"
  "prettier-plugin-tailwindcss": "^0.6.9"
  "tailwindcss": "^3.4.16"
  "clsx": "^2.1.1"

catalogs:
  # react
  react18:
    "react": "^18.3.1"
    "@types/react": "^18.3.12"

  react-dom:
    "react-dom": "^18.3.1"
    "@types/react-dom": "^18.3.1"

  react-native:
    "react-native": "^0.76.4"
    "expo": "^52.0.17"
    "expo-status-bar": "~2.0.0"
    "expo-router": "~4.0.11"
    "jest-expo": "^52.0.2"
    "@expo/webpack-config": "^19.0.1"
    "@expo/vector-icons": "^14.0.2"
    "@testing-library/react-native": "^12.8.1"
    "@react-navigation/bottom-tabs": "^7.1.3"
    "@react-navigation/native": "^7.0.13"
    "expo-blur": "~14.0.1"
    "expo-constants": "~17.0.3"
    "expo-font": "~13.0.1"
    "expo-haptics": "~14.0.0"
    "expo-linking": "~7.0.3"
    "expo-splash-screen": "~0.29.16"
    "expo-symbols": "~0.2.0"
    "expo-system-ui": "~4.0.5"
    "expo-web-browser": "~14.0.1"
    "react-native-gesture-handler": "~2.21.2"
    "react-native-reanimated": "~3.16.3"
    "react-native-safe-area-context": "5.0.0"
    "react-native-screens": "~4.3.0"
    "react-native-web": "~0.19.13"
    "react-native-webview": "13.12.5"

  # react-query
  react-query4:
    "@tanstack/react-query": "^4.36.1"
    "@tanstack/react-query-devtools": "^4.36.1"

  react-query5:
    "@tanstack/react-query": "^5.59.16"
    "@tanstack/react-query-devtools": "^5.59.16"
    "@tanstack/react-query-next-experimental": "^5.59.16"
