name: ci-workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  quality:
    name: Check quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8

      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}
          check-latest: true

      - name: Install dependencies
        run: pnpm install

      - name: Check typescript
        run: pnpm type:check

      - name: Check eslint
        run: pnpm lint

      - name: Test by jest
        run: pnpm test

      - name: Build package
        run: pnpm run build
