name: Compressed Size

on:
  pull_request:
    types: [opened, synchronize, reopened]
env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  CI: ${{ vars.CI }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  size:
    name: Check compressed size
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm-setup-node
      - run: pnpm install --frozen-lockfile

      - name: Report build size
        uses: preactjs/compressed-size-action@v2
        with:
          build-script: 'prepack'
          pattern: 'packages/**/dist/*.{js,cjs,mjs}'
          exclude: '{**/*.map,**/node_modules/**}'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  visualization-app-size:
    name: visualization app size
    runs-on: ubuntu-latest
    needs: size
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm-setup-node
      - run: pnpm install --frozen-lockfile

      - name: Report app size
        uses: preactjs/compressed-size-action@v2
        with:
          build-script: '--filter ./websites/visualization build'
          pattern: '.next/static/chunks/**/*.js'
          strip-hash: "(?:runtime/\\w+-(\\w{20}).js$|chunks/\\w{40}\\.(\\w{20})\\.js$|static/(\\w{20,21})/)"
          exclude: '{**/*.map,**/node_modules/**}'
          use-check: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
