name: release-workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Release to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.5.1
      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'
          node-version-file: '.nvmrc'
      - run: pnpm install --frozen-lockfile

      - name: Set git user
        run: |
          git config --global user.email "manudeli.ko@gmail.com"
          git config --global user.name "Jonghyeon Ko"

      - name: Create Changesets Pull Request or Publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          setupGitUser: false
          title: 'chore(changesets): bump packages version'
          commit: 'chore: bump packages version'
          version: pnpm changeset:version
          publish: pnpm npm:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
