name: Size Comment

on:
  pull_request:
    types: [opened, synchronize, reopened]
env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  CI: ${{ vars.CI }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm-setup-node
      - run: pnpm install --frozen-lockfile
      - name: Report package size
        uses: preactjs/compressed-size-action@v2
        with:
          pattern: 'packages/**/dist/*.{js,cjs,mjs}'
          exclude: '{**/*.map,**/node_modules/**}'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Report package user size
        uses: transferwise/actions-next-bundle-analyzer@v2
        with:
          working-directory: ./websites/visualization
          comment-strategy: 'always'
